### ISSUE TITLE
Libraries has no version info

### ISSUE THREAD

**Issue by dutchiexl** [drupal-composer/drupal-parse-composer#28] opened 2015-02-09 16:09 UTC
For the libraries module, the version is missing when downloaded by composer. This is a problem because alot of other modules depend on this.

**Comment by dutchiexl** [comment] 2015-02-09 16:09
name = Libraries
description = Allows version-dependent and shared usage of external libraries.
core = 7.x
; We use hook_system_theme_info() which was added in Drupal 7.11
dependencies[] = system (>=7.11)
files[] = tests/libraries.test

**Comment by derhasi** [comment] 2015-02-09 16:16
The reason is, as composer uses git as source. It's the same as you'd directly check it out from git on your own.
This is a duplicate of #23 . Workarounds are covered there, but we might need to work on a solid generic solution.

**Closed by derhasi** 2015-02-09 16:16 UTC
Labels: duplicate
